-- V8 Chinese data migration
UPDATE sys_role SET role_code='REGION_DIRECTOR', role_name='地区主管领导', description='可查看整个阿克苏地区所有数据', data_scope='ALL', region_scope='REGION', dept_scope='ALL', org_level='REGION', parent_id=NULL, role_type='BUSINESS', sort_order=10 WHERE id=2;
UPDATE sys_role SET role_code='ENFORCER', role_name='执法人员', description='仅可查看本科室管辖范围内的数据', data_scope='DEPT', region_scope='COUNTY', dept_scope='DEPT', org_level='DEPT', parent_id=6, role_type='BUSINESS', sort_order=50 WHERE id=3;
INSERT IGNORE INTO sys_role (id, role_code, role_name, description, status, parent_id, role_type, data_scope, region_scope, dept_scope, org_level, sort_order) VALUES (4, 'REGION_DEPUTY', '地区分管领导', '分管地区某领域工作，可查看全地区数据', 1, 2, 'BUSINESS', 'ALL', 'REGION', 'ALL', 'REGION', 15);
INSERT IGNORE INTO sys_role (id, role_code, role_name, description, status, parent_id, role_type, data_scope, region_scope, dept_scope, org_level, sort_order) VALUES (5, 'CITY_DIRECTOR', '市级主管领导', '可查看本市所有数据', 1, 2, 'BUSINESS', 'ALL', 'CITY', 'ALL', 'CITY', 20);
INSERT IGNORE INTO sys_role (id, role_code, role_name, description, status, parent_id, role_type, data_scope, region_scope, dept_scope, org_level, sort_order) VALUES (6, 'COUNTY_DIRECTOR', '县/市级主管领导', '可查看本县/市所有数据', 1, 5, 'BUSINESS', 'ALL', 'COUNTY', 'ALL', 'COUNTY', 25);
INSERT IGNORE INTO sys_role (id, role_code, role_name, description, status, parent_id, role_type, data_scope, region_scope, dept_scope, org_level, sort_order) VALUES (7, 'DEPT_CHIEF', '科室负责人', '可查看本科室管辖范围数据', 1, 6, 'BUSINESS', 'DEPT', 'COUNTY', 'DEPT', 'DEPT', 30);
INSERT IGNORE INTO sys_role (id, role_code, role_name, description, status, parent_id, role_type, data_scope, region_scope, dept_scope, org_level, sort_order) VALUES (8, 'DEPT_DEPUTY_CHIEF', '副科长', '可查看本科室管辖范围数据', 1, 7, 'BUSINESS', 'DEPT', 'COUNTY', 'DEPT', 'DEPT', 35);
INSERT IGNORE INTO sys_role (id, role_code, role_name, description, status, parent_id, role_type, data_scope, region_scope, dept_scope, org_level, sort_order) VALUES (9, 'REGION_DEPT_CHIEF', '地区科室负责人', '可查看全地区该科室管辖范围数据', 1, 4, 'BUSINESS', 'ALL', 'REGION', 'DEPT', 'REGION', 32);
INSERT IGNORE INTO sys_role (id, role_code, role_name, description, status, parent_id, role_type, data_scope, region_scope, dept_scope, org_level, sort_order) VALUES (10, 'ENTERPRISE_USER', '企业用户', '企业用户角色，仅可查看自己企业数据', 1, NULL, 'BUSINESS', 'SELF', 'SELF', 'SELF', 'ENTERPRISE', 60);
INSERT IGNORE INTO sys_role (id, role_code, role_name, description, status, parent_id, role_type, data_scope, region_scope, dept_scope, org_level, sort_order) VALUES (11, 'CITY_DEPT_CHIEF', '市级科室负责人', '可查看本市该科室管辖范围数据', 1, 5, 'BUSINESS', 'ALL', 'CITY', 'DEPT', 'CITY', 33);
UPDATE sys_position SET role_id=1 WHERE id=1;
UPDATE sys_position SET role_id=3 WHERE id=4;
UPDATE sys_position SET role_id=7 WHERE id=5;
UPDATE sys_position SET role_id=2 WHERE id=6;
UPDATE sys_job_title SET role_id=2 WHERE id=1;
UPDATE sys_job_title SET role_id=4 WHERE id=2;
UPDATE sys_job_title SET role_id=7 WHERE id=3;
UPDATE sys_job_title SET role_id=8 WHERE id=4;
UPDATE sys_job_title SET role_id=3 WHERE id=5;
UPDATE sys_job_title SET role_id=3 WHERE id=6;
UPDATE sys_job_title SET role_id=3 WHERE id=7;
INSERT IGNORE INTO sys_job_title (id, title_code, title_name, is_leadership, level, role_id, status, sort_order) VALUES (9, 'TITLE-REGION-CHIEF', '地区局局长', 1, 1, 2, 1, 1);
INSERT IGNORE INTO sys_job_title (id, title_code, title_name, is_leadership, level, role_id, status, sort_order) VALUES (10, 'TITLE-REGION-DEPUTY', '地区局副局长', 1, 2, 4, 1, 2);
INSERT IGNORE INTO sys_job_title (id, title_code, title_name, is_leadership, level, role_id, status, sort_order) VALUES (11, 'TITLE-CITY-CHIEF', '市/县局局长', 1, 2, 5, 1, 3);
INSERT IGNORE INTO sys_job_title (id, title_code, title_name, is_leadership, level, role_id, status, sort_order) VALUES (12, 'TITLE-CITY-DEPUTY', '市/县局副局长', 1, 3, 6, 1, 4);
INSERT IGNORE INTO sys_job_title (id, title_code, title_name, is_leadership, level, role_id, status, sort_order) VALUES (13, 'TITLE-KEZHANG', '科长', 1, 4, 9, 1, 5);
INSERT IGNORE INTO sys_job_title (id, title_code, title_name, is_leadership, level, role_id, status, sort_order) VALUES (14, 'TITLE-FUKEZHANG', '副科长', 1, 5, 8, 1, 6);
INSERT IGNORE INTO sys_job_title (id, title_code, title_name, is_leadership, level, role_id, status, sort_order) VALUES (15, 'TITLE-ZHUREN-KEERYUAN', '科室主任科员', 0, 6, 3, 1, 7);
INSERT IGNORE INTO sys_job_title (id, title_code, title_name, is_leadership, level, role_id, status, sort_order) VALUES (16, 'TITLE-KEYYUAN', '科员', 0, 7, 3, 1, 8);
INSERT IGNORE INTO sys_position (id, position_code, position_name, category, level, role_id, status, sort_order) VALUES (8, 'POS-REGION-CHIEF', '地区局局长', 'LEADERSHIP', 1, 2, 1, 1);
INSERT IGNORE INTO sys_position (id, position_code, position_name, category, level, role_id, status, sort_order) VALUES (9, 'POS-REGION-DEPUTY', '地区局副局长', 'LEADERSHIP', 2, 4, 1, 2);
INSERT IGNORE INTO sys_position (id, position_code, position_name, category, level, role_id, status, sort_order) VALUES (10, 'POS-CITY-CHIEF', '市/县局局长', 'LEADERSHIP', 2, 5, 1, 3);
INSERT IGNORE INTO sys_position (id, position_code, position_name, category, level, role_id, status, sort_order) VALUES (11, 'POS-CITY-DEPUTY', '市/县局副局长', 'LEADERSHIP', 3, 6, 1, 4);
INSERT IGNORE INTO sys_position (id, position_code, position_name, category, level, role_id, status, sort_order) VALUES (12, 'POS-KEZHANG', '科长', 'LEADERSHIP', 4, 9, 1, 5);
INSERT IGNORE INTO sys_position (id, position_code, position_name, category, level, role_id, status, sort_order) VALUES (13, 'POS-FUKEZHANG', '副科长', 'LEADERSHIP', 5, 8, 1, 6);
INSERT IGNORE INTO sys_position (id, position_code, position_name, category, level, role_id, status, sort_order) VALUES (14, 'POS-ZHUREN-KEERYUAN', '主任科员', 'GENERAL', 6, 3, 1, 7);
INSERT IGNORE INTO sys_position (id, position_code, position_name, category, level, role_id, status, sort_order) VALUES (15, 'POS-KEYYUAN', '科员', 'GENERAL', 7, 3, 1, 8);
